@api_HostAddress = http://localhost:5064

POST {{api_HostAddress}}/create-repo
Content-Type: application/json
Accept: application/json

{
    "RepoName": "new-pulumi-repo",
    "Private": true,
    "Description": "The description in the README of the repo", //Optionnal
}

POST {{api_HostAddress}}/create-staticweb
Content-Type: application/json
Accept: application/json

{
    "Name":"nomenminiscule" // NO SPECIAL CHAR OR MAJ
}


POST {{api_HostAddress}}/create-ressource
Content-Type: application/json
Accept: application/json

{
    "Name": "my-ressorce",
    "Parameters": {
        "type": "ressource type",
        "parameter1": "parameter",
        "parameter2": "parameter",
        "parameter": "parameter"
    }
}


###